hibernate.connection.url=jdbc:postgresql://192.168.1.54:5432/meat_db
hibernate.connection.username=postgres
hibernate.connection.password=01042004ILipanch
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update